name: Different_OS

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Print Ubuntu Details
        run: |
          echo "The operating system is ${{ runner.os }}"
          hostname
          echo "The user running this job is ${{ github.actor }}"

  second:
    runs-on: windows-latest
    steps:
      - name: Print Windows Details
        run: |
          echo "The operating system is ${{ runner.os }}"
          hostname
          echo "The user running this job is ${{ github.actor }}"

  third:
    runs-on: macos-latest
    steps:
      - name: Print macOS Details
        run: |
          echo "The operating system is ${{ runner.os }}"
          hostname
          echo "The user running this job is ${{ github.actor }}"
