name: PullRequest

on:
  pull_request:
    types: [opened]
    branches: [main]
  
  schedule:
    - cron: '0 9 * * *' 

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: PR Branch Check
        run: echo "PR check running for branch:${{ github.head_ref }}"

      - name: Print On 
        run: |
          echo "${{ github.event.action }}"
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.user.login }}"
          echo "${{ github.action_ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"


