name: Secret

on:
  workflow_dispatch:


jobs:
  Print:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
    steps:
      
      - name: Check Secret
        if: ${{ env.MY_SECRET != '' }}
        run: echo 'The secret is set true'
      - name: Print Secret message
        run: echo "${{ env.MY_SECRET }}"
